"""
HTML report generator.

Produces a self-contained single-file report from results.json.
"""
from __future__ import annotations
import json
from pathlib import Path


def generate_report(results: dict, output_path: str | Path) -> None:
    schema  = results.get("schema", "")
    summary = results.get("summary", {})
    all_results = results.get("results", [])

    persons   = sorted({r["person"]   for r in all_results})
    scenarios = sorted({r["scenario"] for r in all_results})
    result_map = {(r["person"], r["scenario"]): r for r in all_results}

    total     = summary.get("total", 0)
    satisfied = summary.get("satisfied", 0)
    score     = summary.get("score", 0)

    def cell(person, scenario):
        r = result_map.get((person, scenario))
        if not r:
            return "<td class='na'>—</td>"
        ok    = r["satisfied"]
        sc    = r["score"]
        viols = r.get("violations", [])
        tip   = "\\n".join(viols) if viols else "All constraints satisfied"
        cls   = "pass" if ok else "fail"
        sym   = "✓" if ok else "✗"
        return f"<td class='{cls}' title='{tip}'>{sym} {sc:.0%}</td>"

    rows = ""
    for p in persons:
        person_results = [result_map.get((p, s)) for s in scenarios]
        pct = sum(1 for r in person_results if r and r["satisfied"]) / max(len(scenarios), 1)
        rows += f"<tr><td class='person'>{p}</td>"
        for s in scenarios:
            rows += cell(p, s)
        rows += f"<td class='total'>{pct:.0%}</td></tr>"

    col_headers = "".join(f"<th>{s}</th>" for s in scenarios)

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>usersim report</title>
<style>
  body {{ font-family: system-ui, sans-serif; background: #0d1117; color: #e6edf3; margin: 0; padding: 32px; }}
  h1   {{ font-size: 20px; font-weight: 700; margin: 0 0 4px; }}
  .subtitle {{ color: #8b949e; font-size: 13px; margin-bottom: 32px; }}
  .summary {{ display: flex; gap: 24px; margin-bottom: 32px; }}
  .stat    {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px 24px; }}
  .stat .val {{ font-size: 32px; font-weight: 700; color: #58a6ff; }}
  .stat .lbl {{ font-size: 12px; color: #8b949e; margin-top: 2px; }}
  table  {{ border-collapse: collapse; width: 100%; }}
  th     {{ background: #161b22; padding: 10px 16px; font-size: 11px; text-transform: uppercase;
             letter-spacing: .06em; color: #8b949e; border-bottom: 1px solid #30363d; text-align: left; }}
  td     {{ padding: 9px 16px; border-bottom: 1px solid #21262d; font-size: 13px; }}
  td.person {{ font-weight: 600; min-width: 160px; }}
  td.pass   {{ color: #3fb950; text-align: center; }}
  td.fail   {{ color: #f85149; text-align: center; }}
  td.na     {{ color: #484f58; text-align: center; }}
  td.total  {{ font-weight: 700; text-align: center; color: #58a6ff; }}
  tr:hover td {{ background: #161b22; }}
  .score-bar {{ height: 6px; background: #21262d; border-radius: 3px; width: 200px; margin-top: 8px; }}
  .score-fill {{ height: 6px; background: {'#3fb950' if score > 0.8 else '#f0883e' if score > 0.5 else '#f85149'}; border-radius: 3px; width: {score*100:.0f}%; }}
</style>
</head>
<body>
  <h1>usersim report</h1>
  <p class="subtitle">{total} checks across {len(persons)} personas &times; {len(scenarios)} scenarios</p>

  <div class="summary">
    <div class="stat">
      <div class="val">{satisfied}/{total}</div>
      <div class="lbl">Checks satisfied</div>
    </div>
    <div class="stat">
      <div class="val">{score:.0%}</div>
      <div class="lbl">Overall score</div>
      <div class="score-bar"><div class="score-fill"></div></div>
    </div>
    <div class="stat">
      <div class="val">{len(persons)}</div>
      <div class="lbl">Personas</div>
    </div>
    <div class="stat">
      <div class="val">{len(scenarios)}</div>
      <div class="lbl">Scenarios</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Persona</th>
        {col_headers}
        <th>% passed</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <p style="margin-top:32px; font-size:11px; color:#484f58;">
    Generated by usersim &middot; hover cells to see constraint violations
  </p>
</body>
</html>"""

    Path(output_path).write_text(html)
